### ISSUE TITLE
How do I serialize the request that was deserialized by this tool

### ISSUE THREAD

**Issue by zxiong** [leonardopuleggi/GWT-HAR-Parser#1]
It's a cool tool to parse the gwt requests and responses. But I have a question, could I serialize the request that was deserialized by this tool?

For example:

Parsed/ deserialized result from the above request using this tool:
toString() =>
com.polarion.alm.ui.client.tracker.WorkItemDataService.loadInstances([subterra:data-service:objects:/default/perf1${WorkItem}PERF1-1511, subterra:data-service:objects:/default/perf1${WorkItem}PERF1-1510, subterra:data-service:objects:/default/perf1${WorkItem}PERF1-1509], [id, title, priority, severity, status, resolution, author, assignee, timePoint, remainingEstimate, created, updated, type, project, _document, _space], true, ProjectScope perf1)

via reflection =>
com.google.gwt.user.server.rpc.RPCRequest@365c30cc[flags=0,method=public abstract java.util.ArrayList com.polarion.alm.ui.client.tracker.WorkItemDataService.loadInstances(java.util.ArrayList,java.util.ArrayList,boolean,com.polarion.portal.shared.navigation.IScope),parameters={[subterra:data-service:objects:/default/perf1${WorkItem}PERF1-1511, subterra:data-service:objects:/default/perf1${WorkItem}PERF1-1510, subterra:data-service:objects:/default/perf1${WorkItem}PERF1-1509],[id, title, priority, severity, status, resolution, author, assignee, timePoint, remainingEstimate, created, updated, type, project, _document, _space],true,ProjectScope perf1},rpcToken=<null>,serializationPolicy=null]

Then,  how can I get the request before serialization from the above parsed/deserialized result? Since I need modify some parameters.

**Comment by leonardopuleggi** [comment]
Not at the moment. The easiest way is to use the GWT debug or superdev mode and change the parameters from withing your GWT app. Once you have the XHR you can see the serialization with this tool
